version: 0.2
        
phases:
  install:
    commands:
      - echo Install awscli
      - pip install awscli --upgrade
      - aws --version
  build:
    commands:
      - echo Build Start `date`
      - echo ${DUMMY_ENV}
      - echo $DUMMY_ENV
      - sh exec.sh
      - echo Build Finish `date`
